/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2019-05-03

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32l4xx.h"
#include "Types.h"
#include "GPIO.h"
#include "TIMER.h"
#include "INTRPT.h"


/* Private macro */

/* Private variables */

/* Private function prototypes */

/* Private functions */

void System_Clock_Init(void)
{

	/* Enable High Speed Internal Clock (HSI = 16 MHz) */
	RCC->CR |= ((uint32_t)RCC_CR_HSION);

	/* wait until HSI is ready*/
	while ( (RCC->CR & (uint32_t) RCC_CR_HSIRDY) == 0 ) {;}

	/* Select HSI as system clock source*/
	RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_SW));
	RCC->CFGR |= (uint32_t)RCC_CFGR_SW_HSI;  //01: HSI16 oscillator used as system clock

	/* Wait till HSI is used as system clock source*/
	while ((RCC->CFGR & (uint32_t)RCC_CFGR_SWS) == 0 ) {;}

	/* Multi Speed Internal Clock (MSI = 48MHz) */

	/*MSI can be configured when OFF*/
	RCC->CR &= ~(RCC_CR_MSION);

	/*Clear MSIRANGE in CR register and then Configure it for Range 11 ie 48MHz*/
	RCC->CR &= ~(RCC_CR_MSIRANGE);
	RCC->CR |= RCC_CR_MSIRANGE_11;

	/*Select MSI range from CR register*/
	RCC->CR |= RCC_CR_MSIRGSEL;
	/*Turn ON MSI and then wait for it to get Ready*/
	RCC->CR |= (RCC_CR_MSION);
	while((RCC->CR & RCC_CR_MSIRDY) == 0) {;}

	/*Flash wait latency for 48mhz HCLK is 2WS*/
	FLASH->ACR &= ~(FLASH_ACR_LATENCY_0WS);
	FLASH->ACR |= (FLASH_ACR_LATENCY_2WS);

	/*Switch Main clock to MSI*/
	RCC->CFGR &= ~(RCC_CFGR_SW);
	RCC->CFGR |= (uint32_t)RCC_CFGR_SW_MSI;

	return;
}

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/
int main(void)
{
	/**
	*  IMPORTANT NOTE!
	*  The symbol VECT_TAB_SRAM needs to be defined when building the project
	*  if code has been located to RAM and interrupts are used.
	*  Otherwise the interrupt table located in flash will be used.
	*  See also the <system_*.c> file and how the SystemInit() function updates
	*  SCB->VTOR register.
	*  E.g.  SCB->VTOR = 0x20000000;
	*/

	/* TODO - Add your application code here */

	/* System Initialization */
	System_Clock_Init();
	GPIO_Port_Init();
	TIMER_RLT_Init();


	/* Infinite loop */

	while (1)
	{
		/*Do nothing*/
	}
}

